apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: ibm-cp-watson-aiops
  namespace: {{ .Values.namespace }}
spec:
  imagePullSecret: {{ .Values.imagePullSecret }}
  license:
    accept: true
  pakModules:
  - name: aiopsFoundation
    enabled: true
  - name: applicationManager
    enabled: true
  - name: aiManager
    enabled: true
  - name: connection
    enabled: false
  size: small
  storageClass: {{ .Values.storageClass }}
  storageClassLargeBlock: {{ .Values.storageClassLargeBlock }}