apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4waiops-cp-waiops-aimgr-instance
spec:
  destination:
    namespace: cp4waiops
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/cp4waiops/cp-waiops-aimgr-instance
    repoURL: https://github.com/gandhicloudlaborg/gan-sew-cpc-test08
    targetRevision: main
    helm:
      releaseName: cp-waiops-aimgr-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
