apiVersion: v2
name: cp-waiops-aimgr-instance
description: A Helm chart for in install the IBM Cloud Pak for Watson AIOps AI-Manager - Instance
type: application
version: 0.1.1
appVersion: "1.0"
# dependencies:
#   - name: ibm-cp-waiops
#     version: 0.1.0
#     repository: https://charts.cloudnativetoolkit.dev

