apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-marketplace-ibm-cp-catalogs-waiops
spec:
  destination:
    namespace: openshift-marketplace
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/openshift-marketplace/ibm-cp-catalogs-waiops
    repoURL: https://github.com/gandhicloudlaborg/gan-sew-cpc-test08
    targetRevision: main
    helm:
      releaseName: ibm-cp-catalogs-waiops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
