apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-aiops-orchestrator
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.subscription_channel }}
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: {{ .Values.catalog_source }}
  sourceNamespace: openshift-marketplace